### ISSUE TITLE
Blank lines generated in the topic leads to garbage ingestion in Splunk with Java stack traces

### ISSUE THREAD

**Issue by guilhemmarchand** [splunk/kafka-connect-splunk#172]
**Issue description:**

If blank lines are being inserted in the Kafka topic for some reasons, this results in java stack traces in the Kafka connect nodes running the sink connector, and this leads to the generation of garbash messages indexed in Splunk.

Data source origin: Telegraf output in Graphite mode (with tag or without tag support) producing directly to Kafka brokers (Kafka destination)

**Example of data generated in the topic:**

```
disk.used_percent;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 15.111134285569921 1536241860
disk.inodes_total;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 12800000 1536241860
disk.inodes_free;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 12656809 1536241860
disk.inodes_used;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 143191 1536241860
disk.total;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 104022159360 1536241860
disk.free;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 88288989184 1536241860
disk.used;device=nvme0n1p1;fstype=ext4;host=ip-10-0-0-173;mode=rw;path=-var-lib-docker-aufs 15716392960 1536241860

system.uptime;host=ip-10-0-0-173 544794 1536241860


diskio.io_time;_name=nvme0n1;host=ip-10-0-0-173 5222848 1536241860
diskio.iops_in_progress;_name=nvme0n1;host=ip-10-0-0-173 0 1536241860
diskio.write_time;_name=nvme0n1;host=ip-10-0-0-173 84460220 1536241860
diskio.read_time;_name=nvme0n1;host=ip-10-0-0-173 183544 1536241860
diskio.reads;_name=nvme0n1;host=ip-10-0-0-173 107516 1536241860
diskio.writes;_name=nvme0n1;host=ip-10-0-0-173 35479171 1536241860
diskio.write_bytes;_name=nvme0n1;host=ip-10-0-0-173 289396678656 1536241860
diskio.read_bytes;_name=nvme0n1;host=ip-10-0-0-173 2093498368 1536241860
diskio.weighted_io_time;_name=nvme0n1;host=ip-10-0-0-173 84639664 1536241860

diskio.reads;_name=nvme0n1p1;host=ip-10-0-0-173 107301 1536241860
diskio.weighted_io_time;_name=nvme0n1p1;host=ip-10-0-0-173 84600036 1536241860
diskio.iops_in_progress;_name=nvme0n1p1;host=ip-10-0-0-173 0 1536241860
diskio.writes;_name=nvme0n1p1;host=ip-10-0-0-173 33675551 1536241860
diskio.read_bytes;_name=nvme0n1p1;host=ip-10-0-0-173 2087916544 1536241860
diskio.read_time;_name=nvme0n1p1;host=ip-10-0-0-173 183500 1536241860
diskio.io_time;_name=nvme0n1p1;host=ip-10-0-0-173 5182704 1536241860
diskio.write_bytes;_name=nvme0n1p1;host=ip-10-0-0-173 289396674560 1536241860
diskio.write_time;_name=nvme0n1p1;host=ip-10-0-0-173 84418608 1536241860

diskio.writes;_name=loop0;host=ip-10-0-0-173 0 1536241860
diskio.write_time;_name=loop0;host=ip-10-0-0-173 0 1536241860
diskio.io_time;_name=loop0;host=ip-10-0-0-173 32 1536241860
diskio.iops_in_progress;_name=loop0;host=ip-10-0-0-173 0 1536241860
diskio.reads;_name=loop0;host=ip-10-0-0-173 11274 1536241860
diskio.read_bytes;_name=loop0;host=ip-10-0-0-173 12601344 1536241860
diskio.write_bytes;_name=loop0;host=ip-10-0-0-173 0 1536241860
diskio.read_time;_name=loop0;host=ip-10-0-0-173 412 1536241860
diskio.weighted_io_time;_name=loop0;host=ip-10-0-0-173 408 1536241860

```

**In the Kafka nodes stdout, the following JAVA stack traces can be observed:**

```
kafka-connect-1_1  | [2018-09-02 13:52:16,657] ERROR ignore malformed event for topicPartitionOffset=(telegraf, 2, 10323) (com.splunk.kafka.connect.SplunkSinkTask:166)
kafka-connect-1_1  | com.splunk.hecclient.HecException: Empty event
kafka-connect-1_1  |    at com.splunk.hecclient.Event.checkEventData(Event.java:195)
kafka-connect-1_1  |    at com.splunk.hecclient.Event.<init>(Event.java:57)
kafka-connect-1_1  |    at com.splunk.hecclient.RawEvent.<init>(RawEvent.java:22)
kafka-connect-1_1  |    at com.splunk.kafka.connect.SplunkSinkTask.createHecEventFrom(SplunkSinkTask.java:251)
kafka-connect-1_1  |    at com.splunk.kafka.connect.SplunkSinkTask.sendEvents(SplunkSinkTask.java:164)
kafka-connect-1_1  |    at com.splunk.kafka.connect.SplunkSinkTask.handleRaw(SplunkSinkTask.java:147)
kafka-connect-1_1  |    at com.splunk.kafka.connect.SplunkSinkTask.put(SplunkSinkTask.java:85)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
kafka-connect-1_1  |    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
kafka-connect-1_1  |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka-connect-1_1  |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka-connect-1_1  |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kafka-connect-1_1  |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kafka-connect-1_1  |    at java.lang.Thread.run(Thread.java:748)

```

**In Splunk, this leads to index garbash events, example:**

```
timestamp=null, topic='telegraf', partition=0, offset=15389, type=malformeddiskio.write_bytes
timestamp=null, topic='telegraf', partition=0, offset=15404, type=malformeddiskio.read_bytes
timestamp=null, topic='telegraf', partition=0, offset=15440, type=malformeddiskio.read_bytes
timestamp=null, topic='telegraf', partition=0, offset=15450, type=malformeddiskio.weighted_io_time
timestamp=null, topic='telegraf', partition=0, offset=15502, type=malformeddiskio.read_bytes
timestamp=null, topic='telegraf', partition=0, offset=15537, type=malformeddiskio.write_time
timestamp=null, topic='telegraf', partition=0, offset=15576, type=malformeddiskio.writes
timestamp=null, topic='telegraf', partition=0, offset=15630, type=malformeddiskio.read_bytes
timestamp=null, topic='telegraf', partition=0, offset=15649, type=malformeddiskio.iops_in_progress
timestamp=null, topic='telegraf', partition=0, offset=15708, type=malformeddiskio.write_bytes
timestamp=null, topic='telegraf', partition=0, offset=15737, type=malformeddiskio.read_time
timestamp=null, topic='telegraf', partition=0, offset=15759, type=malformeddiskio.read_bytes
timestamp=null, topic='telegraf', partition=0, offset=15801, type=malformedprocesses.sleeping
timestamp=null, topic='telegraf', partition=0, offset=15817, type=malformeddiskio.weighted_io_time
timestamp=null, topic='telegraf', partition=0, offset=15878, type=malformeddiskio.write_time
timestamp=null, topic='telegraf', partition=0, offset=15894, type=malformeddiskio.reads 

```

**The following Splunk transform can be used as a workaround to send the garbash data to null queue:**

```
[kafka_empty_malformed_setnull]
REGEX = ^timestamp=null
LOOKAHEAD = 14
DEST_KEY = queue
FORMAT = nullQueue

```
**Reproducing:**

You can easily reproduce the issue by using the following TA I have created and ingesting Telegraf metrics to Kafka, all information are in the Readme and documentation of the ITSI module I have developed as well:

https://github.com/guilhemmarchand/TA-influxdata-telegraf

https://da-itsi-telegraf-os.readthedocs.io/en/latest/telegraf.html#kafka-ingestion

**Comment by chaitanyaphalak** [comment]
resolved as part of https://github.com/splunk/kafka-connect-splunk/pull/229
