### ISSUE TITLE
Unable to forward Avro data to splunk

### ISSUE THREAD

**Issue by srn01** [splunk/kafka-connect-splunk#195]
Hi 
I am unable to forward data in avro format.Although i am able to forward it as string
It shows below error message

We have tried cosume data using a java code which uses confluent schema registry url and where able to consume.

But while using kafka-connect-splunk jar with below distributed properties
"key.converter": "io.confluent.connect.avro.AvroConverter",
"key.converter.schema.registry.url": "http://schema-registry:8081",
"value.converter": "io.confluent.connect.avro.AvroConverter",
"value.converter.schema.registry.url": "http://schema-registry:8081",

Please note the data in topic is in avro format .Data is loaded into topic using conflent schema registry to serialize data in avro format
Error message-

[2019-06-27 03:50:24,818] ERROR WorkerSinkTask{id=kafka-connect-splunk-1} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.DataException: <"Topic Name">
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:96)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:453)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

**Comment by chaitanyaphalak** [comment]
Closing issue as its very old. If you need help please reopen the issue/create a new issue. Thanks.
