### ISSUE TITLE
ConcurrentModificationException error on multi-threaded HEC polling

### ISSUE THREAD

**Issue by zigarn** [splunk/kafka-connect-splunk#257]
Connector v2.0

Connector config:

```json
{
    "connector.class": "com.splunk.kafka.connect.SplunkSinkConnector",
    "errors.deadletterqueue.context.headers.enable": "true",
    "errors.deadletterqueue.topic.name": "KCONNECTDLQ",
    "errors.tolerance": "all",
    "name": "splunk-connect",
    "splunk.header.support": "true",
    "splunk.hec.ack.enabled": "true",
    "splunk.hec.ack.poll.threads": "4",
    "splunk.hec.max.http.connection.per.channel": "6",
    "splunk.hec.raw": "true",
    "splunk.hec.raw.line.breaker": "#~sep~#",
    "splunk.hec.threads": "4",
    "splunk.hec.token": "DoNotLookAtMyP@@55w0rd",
    "splunk.hec.total.channels": "6",
    "splunk.hec.track.data": "false",
    "splunk.hec.uri": "https://hec.splunk.mycompany.com:8088",
    "splunk.indexes": "index",
    "splunk.sources": "kafka",
    "splunk.sourcetypes": "json",
    "tasks.max": "9",
    "topics": "TO_SPLUNK",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false"
  }
```

I get those errors:

```
[2020-10-29 10:31:06,787] INFO [splunk-connect|task-2] start polling 42 outstanding acks for 1 channels (com.splunk.hecclient.HecAckPoller:257)
[2020-10-29 10:31:06,787] INFO [splunk-connect|task-2] polling 42 acks for channel=eecb43e5-a739-4ba3-b813-74cf98371ece on indexer=https://hec.splunk.mycompany.com:8088 (com.splunk.hecclient.HecAckPoller:269)
[2020-10-29 10:31:06,800] INFO [splunk-connect|task-2] polled 41 acks for channel=eecb43e5-a739-4ba3-b813-74cf98371ece on indexer=https://hec.splunk.mycompany.com:8088 (com.splunk.hecclient.HecAckPoller:338)
[2020-10-29 10:31:06,801] ERROR [splunk-connect|task-2] failed to poll ack for channel=eecb43e5-a739-4ba3-b813-74cf98371ece on indexer=https://hec.splunk.mycompany.com:8088 (com.splunk.hecclient.HecAckPoller:301)
java.util.ConcurrentModificationException
        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1244)
        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1239)
        at com.splunk.kafka.connect.KafkaRecordTracker.removeAckedEventBatch(KafkaRecordTracker.java:68)
        at com.splunk.kafka.connect.KafkaRecordTracker.removeAckedEventBatches(KafkaRecordTracker.java:49)
        at com.splunk.kafka.connect.SplunkSinkTask.onEventCommitted(SplunkSinkTask.java:350)
        at com.splunk.hecclient.HecAckPoller.handleAckPollResult(HecAckPoller.java:356)
        at com.splunk.hecclient.HecAckPoller.handleAckPollResponse(HecAckPoller.java:328)
        at com.splunk.hecclient.HecAckPoller.access$000(HecAckPoller.java:32)
        at com.splunk.hecclient.HecAckPoller$RunAckQuery.run(HecAckPoller.java:298)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

My configuration may be inconsistent, but was not seeing those errors in v1.2.0 (but it's normal as it didn't existed in v1.2.0).
I have the same problem with `splunk.hec.ack.poll.threads = 1`, but it disappear with `splunk.hec.threads = 1`.

From the code, `all` is a `ConcurrentHashMap`, but the values are `TreeMap` and when iterating over it in multiple threads, if one remove an entry (line 72 of `src/main/java/com/splunk/kafka/connect/KafkaRecordTracker.java`), then things can go wrong.

**Comment by cheneysplunk** [comment]
Thanks @zigarn . Make sense to me. I filed a ticket https://jira.splunk.com/browse/ADDON-30535

**Comment by zigarn** [comment]
@cheneysplunk : I proposed a fix with PR #258 

I can confirm that in the same conditions, no concurrency issue with the fix.

**Comment by moreda** [comment]
Hi, @zigarn.
I'm working on an issue related to events tied to closed partitions (to be filed) and I found yours.

At some point, the calculation of the new offsets –based on the acked event batches– relies on the sorted entries of `Map<Long, EventBatch>` hence the original usage of `TreeMap`. I think that in order to solve the problem that you've found it's better to use `ConcurrentSkipListMap` so you'll keep a sorted map.

Of course, maybe I'm wrong, but it just popped to me that there's this part in the code where the actual order of the entries is important. 😄

**Comment by zigarn** [comment]
Thanks for the feedback @moreda !

I changed the implementation and made the ordering constraint more visible by using `ConcurrentNavigableMap` interface in declaration.

**Comment by chaitanyaphalak** [comment]
@moreda Thanks for pointing out that the ordering is an important consideration.
@zigarn Thanks for the PR, we will look into it 👍

**Comment by zigarn** [comment]
@chaitanyaphalak : is there a bugfix release planned with this fix?

**Comment by chaitanyaphalak** [comment]
The release is out - https://github.com/splunk/kafka-connect-splunk/releases/tag/v2.0.1
