### ISSUE TITLE
com.splunk.hecclient.HecException: linked blocking event queue is full, failed to offer batch into queue

### ISSUE THREAD

**Issue by waewoo** [splunk/kafka-connect-splunk#362]
Hello.
​
I regularly have this type of error (linked blocking event queue is full), which is then followed by an error concerning a java memory problem (Posting Resource Exhausted event: Java heap space) ... which then causes the connector crash.
​
What could have caused this type of error? What parameters need to be changed to avoid this type of error?
​
thank you

```
[splunk-connect|task-0] failed to send batch f376ab93-31f4-4ac5-9425-c7682a2efd13 (com.splunk.kafka.connect.SplunkSinkTask:316)
com.splunk.hecclient.HecException: linked blocking event queue is full, failed to offer batch into queue
                at com.splunk.hecclient.ConcurrentHec.send(ConcurrentHec.java:63)
                at com.splunk.kafka.connect.SplunkSinkTask.send(SplunkSinkTask.java:312)
                at com.splunk.kafka.connect.SplunkSinkTask.sendEvents(SplunkSinkTask.java:304)
                at com.splunk.kafka.connect.SplunkSinkTask.handleRecordsWithHeader(SplunkSinkTask.java:207)
                at com.splunk.kafka.connect.SplunkSinkTask.handleRaw(SplunkSinkTask.java:170)
                at com.splunk.kafka.connect.SplunkSinkTask.put(SplunkSinkTask.java:110)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
                at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
                at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
```

`[4329.092s][error][jvmti] Posting Resource Exhausted event: Java heap space`

**Comment by VihasMakwana** [comment]
Closing as this is made configurable https://github.com/splunk/kafka-connect-splunk/pull/387
