### ISSUE TITLE
HecAckPoller stopped and memory and cpu increase

### ISSUE THREAD

**Issue by waewoo** [splunk/kafka-connect-splunk#378]
Apache kafka version : 3.3.1
Splunk connector version : 2.0.9

Hello.
​
We encounter this type of problem on a regular basis.
​
The HecAckPoller stops and then the memory and cpu used by kafka connect increases to 100%...  but no longer processes the messages.
​
What could be the cause of this problem?
​
thank you

```
[2023-01-26T08:46:48,623Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] [Consumer clientId=connector-consumer-AP12110-splunk-connect-LA-8-prd-bp2i-5, groupId=connect-AP12110-splunk-connect-LA-8-prd-bp2i] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:1050)
[2023-01-26T08:47:17,968Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] [Consumer clientId=connector-consumer-AP12110-splunk-connect-LA-8-prd-bp2i-5, groupId=connect-AP12110-splunk-connect-LA-8-prd-bp2i] Disconnecting from node 2147483645 due to request timeout. (org.apache.kafka.clients.NetworkClient:797)
[2023-01-26T08:47:17,969Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] [Consumer clientId=connector-consumer-AP12110-splunk-connect-LA-8-prd-bp2i-5, groupId=connect-AP12110-splunk-connect-LA-8-prd-bp2i] Cancelled in-flight LEAVE_GROUP request with correlation id 481495 due to node 2147483645 being disconnected (elapsed time since creation: 29998ms, elapsed time since send: 30002ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-01-26T08:47:17,969Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] [Consumer clientId=connector-consumer-AP12110-splunk-connect-LA-8-prd-bp2i-5, groupId=connect-AP12110-splunk-connect-LA-8-prd-bp2i] Group coordinator kafka-2-mh-wxlfgcxnqzxgyjbnhmbj.private.eu-fr2.messagehub.appdomain.cloud:9093 (id: 2147483645 rack: null) is unavailable or invalid due to cause: null.isDisconnected: true. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:947)
[2023-01-26T08:47:17,971Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] App info kafka.consumer for connector-consumer-AP12110-splunk-connect-LA-8-prd-bp2i-5 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
[2023-01-26T08:47:17,971Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] [Producer clientId=connector-dlq-producer-AP12110-splunk-connect-LA-8-prd-bp2i-5] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms. (org.apache.kafka.clients.producer.KafkaProducer:1249)
[2023-01-26T08:47:17,971Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] App info kafka.producer for connector-dlq-producer-AP12110-splunk-connect-LA-8-prd-bp2i-5 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
[2023-01-26T08:47:48,002Z] ERROR [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] failed to process http response (com.splunk.hecclient.Indexer:239)
java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1454)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:205)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
        at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
        at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
        at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
        at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:232)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:270)
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:290)
        at com.splunk.hecclient.Indexer.readAndCloseResponse(Indexer.java:237)
        at com.splunk.hecclient.Indexer.executeHttpRequest(Indexer.java:198)
        at com.splunk.hecclient.Indexer.send(Indexer.java:147)
        at com.splunk.hecclient.HecChannel.send(HecChannel.java:61)
        at com.splunk.hecclient.LoadBalancer.send(LoadBalancer.java:114)
        at com.splunk.hecclient.Hec.send(Hec.java:235)
        at com.splunk.hecclient.ConcurrentHec.send(ConcurrentHec.java:101)
        at com.splunk.hecclient.ConcurrentHec.run(ConcurrentHec.java:93)
        at com.splunk.hecclient.ConcurrentHec.lambda$new$1(ConcurrentHec.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2023-01-26T08:47:48,003Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] add 1 failed batches (com.splunk.kafka.connect.SplunkSinkTask:390)
[2023-01-26T08:47:48,003Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] total failed batches 1 (com.splunk.kafka.connect.KafkaRecordTracker:95)
[2023-01-26T08:47:48,003Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] HecAckPoller stopped with 290 outstanding un-ACKed events (com.splunk.hecclient.HecAckPoller:97)
[2023-01-26T08:47:48,004Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] LoadBalancer stopped (com.splunk.hecclient.LoadBalancer:201)
[2023-01-26T08:47:48,005Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] add 1 failed batches (com.splunk.kafka.connect.SplunkSinkTask:390)
[2023-01-26T08:47:48,005Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] total failed batches 2 (com.splunk.kafka.connect.KafkaRecordTracker:95)
[2023-01-26T08:47:48,005Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] healthcheck failed for https://s01vl9989071.fr.net.intra:8088 indexer, removing this indexer and its channels from the loadbalancer (com.splunk.hecclient.LoadBalancer:161)
[2023-01-26T08:47:48,005Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] HecAckPoller stopped with 2474 outstanding un-ACKed events (com.splunk.hecclient.HecAckPoller:97)
[2023-01-26T08:47:48,007Z] ERROR [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] encountered exception when checking health of indexer Connection pool shut down, this means indexer and its channels are removed from the loadbalancer (com.splunk.hecclient.LoadBalancer:137)
[2023-01-26T08:47:48,008Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] add 1 failed batches (com.splunk.kafka.connect.SplunkSinkTask:390)
[2023-01-26T08:47:48,008Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] total failed batches 3 (com.splunk.kafka.connect.KafkaRecordTracker:95)
[2023-01-26T08:47:48,008Z] INFO [AP12110-splunk-connect-LA-8-prd-bp2i|task-5] HecAckPoller stopped with 0 outstanding un-ACKed events (com.splunk.hecclient.HecAckPoller:97)
```

**Comment by VihasMakwana** [comment]
Hello @waewoo,
Can you provide the task configuration you're using?

**Comment by VihasMakwana** [comment]
Closing as it's inactive for a while. Please reopen if needed
